from screen_display import Screen_Display
from track_manager import Track_Manager, FileSystemItem
import time

ROOT = "./audio"

track_manager = Track_Manager(ROOT)
screen_display = Screen_Display(track_manager)

init_content: list[FileSystemItem] = track_manager.get_init()
screen_display.set_row_1(track_manager.get_init()[0].name)
screen_display.set_row_2(track_manager.get_init()[1].name)
screen_display.scroll_down()
screen_display.scroll_down()
screen_display.scroll_down()
screen_display.scroll_down()
screen_display.select()
time.sleep(1)
screen_display.go_back()
time.sleep(0.5)
screen_display.scroll_down()
time.sleep(0.5)
screen_display.scroll_down()
time.sleep(0.5)
screen_display.scroll_down()
time.sleep(0.5)
screen_display.scroll_down()
time.sleep(0.5)
screen_display.scroll_down()
time.sleep(0.5)
screen_display.scroll_down()
time.sleep(0.5)
screen_display.scroll_up()
time.sleep(0.5)
screen_display.scroll_up()
time.sleep(0.5)
screen_display.scroll_up()
time.sleep(0.5)
screen_display.scroll_up()
time.sleep(0.5)
screen_display.scroll_up()
time.sleep(0.5)
screen_display.scroll_up()
time.sleep(0.5)
screen_display.scroll_up()
time.sleep(0.5)
screen_display.scroll_up()

